test

diff --git a/.github/actions/restore-node/action.yml b/.github/actions/restore-node/action.yml
--- a/.github/actions/restore-node/action.yml
+++ b/.github/actions/restore-node/action.yml
@@ -181,13 +181,23 @@ runs:
         mkdir -p node_modules/.cache/agoric
         date > node_modules/.cache/agoric/yarn-built
 
-    - name: Validate Git Tree Cleanliness
-      uses: pyTooling/Actions/with-post-step@v0.4.5
-      with:
-        main: |
-          bash "$SRC/.github/actions/restore-node/check-git-status.sh" "$SRC" "$IGNORE_DIRTY_YARN_LOCK"
-        post: |
-          bash "$SRC/.github/actions/restore-node/check-git-status.sh" "$SRC" "$IGNORE_DIRTY_YARN_LOCK"
-      env:
-        SRC: ${{ inputs.path }}
-        IGNORE_DIRTY_YARN_LOCK: ${{ steps.endo-branch.outputs.result == 'master' }}
+    - name: git dirty check
+      working-directory: ${{ inputs.path }}
+      shell: bash
+      run: |-
+        echo "Current Working DIR"
+        pwd
+        echo "Current git status"
+        git status
+        set -x
+        # Fail if `git status` reports anything other than the following:
+        # * an untracked endo-sha.txt from above
+        # * work tree files that have been staged without further changes
+        #   (e.g., package.json or yarn.lock) as indicated by the Y position
+        #   in "XY PATH" being a space
+
+        if [ -n "$(git status --porcelain | grep -vE '^[?][?] endo-sha.txt$|^. '; true)" ]; then
+          git status
+          echo "Unexpected dirty git status" 1>&2
+          exit 1
+        fi
