feat(scripts): Update get-released-tags to require tag presence

diff --git a/scripts/get-released-tags b/scripts/get-released-tags
--- a/scripts/get-released-tags
+++ b/scripts/get-released-tags
@@ -3,6 +3,7 @@
 # Invokes `echo` or a specified other command with a list of "...@<version>" and
 # "v<version>" tags associated with the HEAD commit, specifically handling
 # "@agoric/sdk@<version>" tags in a dedicated invocation for CI convenience.
+# Fails if either expected tag category is empty.
 cmd=${1:-echo}
 [ $# -gt 0 ] && shift
 sdkTags=
@@ -13,6 +14,14 @@ for tag in $(git tag -l --contains HEAD | grep -E '(@|^v)[0-9.]+(-[^.]*\.[0-9.]+
 	*) otherTags="$otherTags $tag" ;;
 	esac
 done
+
+errors=
+[ -z "$sdkTags" ] && errors="$(printf '%s%s\n' "$errors" 'No @agoric/sdk tags!')"
+[ -z "$otherTags" ] && errors="$(printf '%s%s\n' "$errors" 'No non-@agoric/sdk tags!')"
+if [ -n "$errors" ]; then
+	echo 1>&2 "$errors"
+	exit 1
+fi
 
 # Push the SDK tag separately so that it can trigger CI.
 "$cmd" "$@" $otherTags && "$cmd" "$@" $sdkTags
