fix: chain registry is not available
- request to http://localhost:8081/chains/agoriclocal failed, reason: connect ECONNREFUSED ::1:8081

diff --git a/.github/workflows/multichain-e2e.yml b/.github/workflows/multichain-e2e.yml
--- a/.github/workflows/multichain-e2e.yml
+++ b/.github/workflows/multichain-e2e.yml
@@ -34,9 +34,9 @@ jobs:
         run: yarn lint
         working-directory: ./agoric-sdk/multichain-testing
 
-      - name: Set Up Starship Infrastructure
+      - name: Setup Starship Infrastructure
         id: starship-infra
-        uses: cosmology-tech/starship-action@0.2.19
+        uses: cosmology-tech/starship-action@0.3.0
         with:
           # uses ghcr.io/agoric/agoric-sdk:dev image (latest master)
           values: ./agoric-sdk/multichain-testing/config.yaml
@@ -51,6 +51,13 @@ jobs:
           kubectl get pods
           make fund-provision-pool
         working-directory: ./agoric-sdk/multichain-testing
+
+      - name: Ensure ports are forwarded
+        run: |
+          curl --fail --retry 3 --retry-delay 10 http://localhost:26657/status || (echo "agoriclocal node is available")
+          curl --fail --retry 3 --retry-delay 10 http://localhost:8081/chains/agoriclocal || (echo "agoriclocal URL check failed")
+          curl --fail --retry 3 --retry-delay 10 http://localhost:8081/chains/osmosislocal || (echo "osmosislocal URL check failed")
+          curl --fail --retry 3 --retry-delay 10 http://localhost:8081/chains/gaialocal || (echo "gaialocal URL check failed")
 
       - name: Run @agoric/multichain-testing E2E Tests
         run: yarn test
